name: Docker Build and Deploy to Kubernetes

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Extract image name from docker-compose.yml
        id: extract-image-name
        run: |
          export IMAGE_NAME=$(grep 'image:' docker-compose.yml | head -n 1 | awk '{print $2}' | sed 's/:.*//')
          echo "image_name=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build container image
        run: |
          docker compose build
          docker tag ${{ env.image_name }}:latest registry.digitalocean.com/loop-prod-registry/${{ env.image_name }}:${{ github.ref_name }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: dop_v1_02ead62742e79165dbafc2900dbcb2f327d647dd44e0fede2571c76eb9e4f44f

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/loop-prod-registry/${{ env.image_name }}:${{ github.ref_name }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-prod

      - name: Deploy to Kubernetes
        run: |
          kubectl -n ${{ github.ref_name }} rollout restart deployment/${{ env.image_name }}
